spring:
  application:
    name: space-cats-marketplace
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/spacemarket
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
springdoc:
  swagger-ui:
    url: /api-specs/product-api-specs.yml
feature:
  toggles:
    cosmoCats: true
    kittyProducts: false
    spring:
